name: TopSky Report
description: Report a bug or required change for TopSky.
title: "[TOPSKY]: "
labels: ["bug", "TopSky"]
body:
  - type: markdown
    attributes:
      value: "# TopSky Report"
  - type: markdown
    attributes:
      value: "Before reporting a bug, ensure that you have the correct [EuroScope version](http://kuwait-iraqvacc.net/Controller%20Guidance/Software/EuroScope%20Setup/) and that you have the latest sectorfile installed."
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug or change required.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Provide steps to reproduce the behavior, if applicable.
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: sectorfile-airac
    attributes:
      label: Sectorfile AIRAC
      description: What sectorfile version are you using?
      placeholder: e.g. 2606
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
